### ISSUE TITLE
Process not stopping after Error: "404 Not Found"

### ISSUE THREAD

**Issue by wieluk** [qcif/nextcloud-sync-cron#13]
Hi, first thanks for your script :)
But I am having trouble sometimes with it. The process just runs forever so it doesn't try again if a error happens. Is it possible to give the process a timeout time?

Here is the problem I am having. To be honest i am not sure what is causing it. I have 4 cron jobs with your script for different directories. Only for my Documents directory I am running into this problem.

```
04-24 11:54:06:423 [ info nextcloud.sync.networkjob ]:  OCC::GetFolderEncryptStatusJob created for "http://192.168.0.37" + "remote.php/webdav" ""
04-24 11:54:06:424 [ info nextcloud.sync.propagator ]:  Starting INSTRUCTION_SYNC propagation of "Wohnung/folder 65/private.pdf" by OCC::PropagateDownloadFile(0x559ab823a0)
04-24 11:54:06:424 [ info nextcloud.sync.accessmanager ]:       6 "PROPFIND" "http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65" has X-Request-ID "283de58f-704b-4dfd-9cc9-4ce35bea497d"
04-24 11:54:06:424 [ info nextcloud.sync.networkjob ]:  OCC::GetFolderEncryptStatusJob created for "http://192.168.0.37" + "remote.php/webdav" ""
04-24 11:54:06:588 [ warning nextcloud.sync.networkjob ]:       QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65\"" QVariant(int, 404)
04-24 11:54:06:588 [ info nextcloud.sync.networkjob.clientsideencrypt ]:        GetFolderEncryptStatus of QUrl("http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65") finished with status QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65\""
04-24 11:54:06:588 [ warning nextcloud.sync.networkjob.clientsideencrypt ]:     *not* successful, http result code is 404 ""
04-24 11:54:06:646 [ warning nextcloud.sync.networkjob ]:       QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65\"" QVariant(int, 404)
04-24 11:54:06:646 [ info nextcloud.sync.networkjob.clientsideencrypt ]:        GetFolderEncryptStatus of QUrl("http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65") finished with status QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND http://192.168.0.37:8997/remote.php/webdav/Wohnung/folder 65\""
04-24 11:54:06:646 [ warning nextcloud.sync.networkjob.clientsideencrypt ]:     *not* successful, http result code is 404 ""
```

I think it has something to do with if files are changed while trying to sync? or something like that.

Edit: even if I kill the process manually I get the same error again with a new process ID so it is not about the process running forever.

**Comment by hoylen** [comment]
I suggest trying to run the sync manually, to isolate the problem. I think the "runs forever" and those errors are an issue with Nextcloud and nothing to do with the _nextcloud-sync-cron.sh_ script. It is a problem Nextcloud is having with that one directory, since your other directories work fine.

All _nextcloud-sync-cron.sh_ does is invoke the _nextcloudcmd_ program with a bunch of options... plus getting those options from a config file, preventing two processes from running, saving the output to a log file, etc.

It calls _nextcloudcmd_ in lines 592 to 613. Probably the easiest way to see the option it uses is to manually invoke the script with `bash -x nextcloud-sync-cron.sh ...` where the `...` are the same arguments you use in your _cron_ job. In the output, find the part where it invokes _nextcloudcmd_ and copy that and run it yourself.
