### ISSUE TITLE
exclude list not working anymore

### ISSUE THREAD

**Issue by wieluk** [qcif/nextcloud-sync-cron#16]
hey, everything worked fine but suddenly the local exclude list doesn't work anymore.

Torrent
docker
octoprint/timelapse
octoprint/logs

my list looks like this but since today it started syncing the folders all the folders on the list. I didn't change anything. do you have a idea why it could happen?

**Comment by hoylen** [comment]
Since the _nextcloud-sync-cron.sh_ script has not changed, I suspect either Nextcloud's _nextcloudcmd_ program, the Nextcloud server/service or both, have changed.

I suggest running the _nextcloud-sync-cron.sh_ script manually (i.e. not in a _cron_ job), but getting it to print out all the commands it runs. That is, instead of running it like `./nextcloud-sync-cron.sh ...` run it like `bash -x ./nextcloud-sync-cron.sh ...`. Find the "nextcloudcmd" command that is printed out.

Then manually run the "nextcloudcmd" with those same options and arguments. If the exclude list still doesn't work (and you will see them being referred to in those options and arguments) then you would have clearly confirmed the problem had nothing to do with the _nextcloud-sync-cron.sh_ script.

Then check if the "nextcloudcmd" you are using has recently been changed or upgraded, before investigating if the Nextcloud server/service has changed.
