### ISSUE TITLE
missing value for "local": /home/user/myncs.conf

### ISSUE THREAD

**Issue by Niko72** [qcif/nextcloud-sync-cron#18]
Running the script, I get the following error : `missing value for "local": /home/user/myncs.conf` But the local setting within `myncs.conf` is the same as I am using for `nextcloudcm` without an error. Therefore, I think that it must be another reason for the error message.

I changed the line 559 within `nextcloud-sync-cron.sh` from `DAVPATH_OPTION="--davpath \"$DAVPATH\""` to `DAVPATH_OPTION="--path \"$DAVPATH\""` as mentioned for newest `nextcloudcm` version 3.5.4 here : [https://github.com/qcif/nextcloud-sync-cron/issues/17#issue-1362012912] but without success. And it looks like there is no other version for focal to downgrade.

Any suggestion out there?

**Comment by hoylen** [comment]
I think the error message is correct: your config file (the file named "/home/user/myncs.comf") is missing the attribute called "local".

That _nextcloud-sync-cron_ config file is **not** the same config file for running _nextcloudcmd_ --- they are two different script/programs and therefore have different things in their config files.

**Comment by Niko72** [comment]
My `myncs.conf` file which does not work:

`local: /home/user/Nextcloud/` with `remote: https://cloud.domain.net` started by `./nextcloud-sync-cron.sh /home/user/myncs.conf`

and my `nextcloudcmd` with the same local path `/home/user/Nextcloud/` works:

`nextcloudcmd -u username -p 'password' /home/user/Nextcloud/ https://cloud.domain.net`

Have I misunderstood something?

**Comment by hoylen** [comment]
Seems ok. Maybe something wrong with the syntax of the file (e.g. CR-LF vs LF line endings, hidden characters).

1. Try deleting the line and retyping it in again (without using copy and paste).
2. Deliberately putting rubbish in the beginning of the file, to make sure it is really using the config file you _think_ it is using.
3. Try it without the slash on the end of the path.
4. Run the script as "sh -x nextcloud-sync-cron" and track down why it thinks "local" is not set. It will be because the test in line 173 fails, but why does it fail?
