### ISSUE TITLE
missunderstanding of bash "-n" test in script?

### ISSUE THREAD

**Issue by philrasch** [qcif/nextcloud-sync-cron#3]
I am a beginner in bash (but quite experienced in other shells). I think there might be a missuse in the sync script. The issue is that the script often uses the syntax "-n $XXX" , where $XXX is a shell variable. In the version of bash I am using [GNU bash, version 4.4.12(1)], it always returns returns true if it is invoked with just a variable name, which I dont think was intended. For example, the command

[ -n $XXX ]; echo $?

will always return 0, whether $XXX is defined or not, and whether it contains a string of length greater than 0.  I think your intent using a -n test was often to check to make sure that variables have a valid filename, and if they do, to make use of it.  In this case I think the correct syntax is to make the test check the contents of variable $XXX by putting double quote marks around it, so in my example you would use

[ -n "$XXX" ]; echo $?

In this case the check will echo 0 or 1, depending on whether $XXX has been defined.  The original script failed when I tested it because I had not defined a "$UNSYNCEDFOLDERS" file and the script built a commandline with an unsyncfolders option containing an empty filename (and the nextcloudcmd command failed on a syntax error). When I added quote marks around the variable name things worked.

I am too inexperienced to be confident that I am correctly diagnosing the problem (but I think I got it right).  Perhaps this will be useful

Phil

**Comment by hoylen** [comment]
Thanks for asking about this.

The `-n` test produces true if the length of the string is non-zero.

The tests should all be for something like `"$VARIABLENAME"`, where the $ expands out the value of the variable and the double quotes is necessary if the value is the empty string, contains whitespace, or is not defined (otherwise there won't be one option to the _-n_ and there a syntax error will occur).

Try running the following, with the first two lines commented out (i.e. variable is not defined), the first line uncommented (i.e. it has a non-zero length value) and the second line uncommented (i.e. its value is the empty string).

```
# ALPHA=foobar
# ALPHA=

if [ -n "$ALPHA" ]; then
  echo "alpha is set"
else
  echo "alpha is zero-length"
fi
```

Which line was giving you a problem? There might be a different bug there.

**Comment by alex-dacosta** [comment]
I'm not a specialist neither.
For having the script to work, since I have` $UNSYNCEDFOLDERS `empty, I changed the line 390 from
`if [ -n "$UNSYNCEDFOLDERS" ]; then`
to
`if [ ! -z "$UNSYNCEDFOLDERS" ]; then`
Am I wrong?
A

**Comment by hoylen** [comment]
That change does not affect the logic. They both mean the same thing, since `-n` and `-z` are the opposite tests of each other.

But I see what was wrong with my original code: it didn't have the double quotes around the variable being tested (it said `if [ -n $UNSYNCEDFOLDERS ]` instead of `if [ -n "$UNSYNCEDFOLDERS" ]`, so when the environment variable is not defined the test is not being performed on an empty string (i.e. `if [ -n "" ]`, which was the intention) but on nothing at all (i.e. `if [ -n ]`, which is a syntax error).

I've added the double quotes and updated it in GitHub.

Thanks for reporting the problem.
