### ISSUE TITLE
davpath option syntax

### ISSUE THREAD

**Issue by miche7** [qcif/nextcloud-sync-cron#4]
Hello,

And first of all, congratulations and thank you for your work.
I would like to know how the exact syntax should appear for a particular folder with the davpath option

Thanking you

Yours,

**Comment by hoylen** [comment]
Sorry, I've never used that feature: it was a someone someone else wanted.

It simply passes that value to the `--davpath` option for the Nextcloud command line client. But the only documentation I've seen on it is at <https://docs.nextcloud.com/desktop/2.5/advancedusage.html#nextcloud-command-line-client> which only says it "overrides the WebDAV Path with" it.

According to one [article](https://support.bigcommerce.com/s/article/File-Access-WebDAV) it looks something like `https://example.com/dav` (the permanent URL to the store followed by "/dav"). If you need to use it (because the Nextcloud server has been configured to use a different WebDAV Path than the default), then the people running your Nextcloud server will probably have to tell you what non-default value they have used.
