### ISSUE TITLE
Issue syncing

### ISSUE THREAD

**Issue by killmasta93** [qcif/nextcloud-sync-cron#7]
Hi 
Currently trying to migrate samba server to nextcloud, as i tried using webdav with rsync but way to slow, so im going to try the nextcloud client but as its a server no WebGUI i would need to use the nextcloudcmd
i saw your script and which i need to sync my local files to the new nextcloud server but im not sure if i did this correctly

1) i downloaded the script
2) created a configfile

# Config file for Nextcloud sync cron

```
local: /opt
remote: https://192.168.3.95
username: cloud
password: mypass
trust: true

```
then run this command 
`
./nextcloud-sync-cron.sh --verbose configfile `

but it get stuck there does not show any output

Currently running it on ubuntu 16.04 LTS

Thank you

**Comment by hoylen** [comment]
> trying to migrate samba server to next cloud

You probably don't need the _nextcloud-sync-cron.sh_ for a migration, since that just involves copying the files across once. The script is designed to be run periodically, e.g. as a _cron_ job, to keep a directory synchronised with Nextcloud as changes are made on either side.

Firstly, you can see what the script is doing by running `bash -x nextcloud-sync-cron.sh --verbose configfile`. You'll  see that all it does is invoke the _nextcloudcmd_, which you can do directly.

Secondly, I suspect it is working. It doesn't print out anything if it runs properly. And if you are migrating a large amount of data, the first time it runs it will take a very long time. It might appear to be stuck, but is really transferring files. Your network bandwidth and disk access speeds are going to dictate how long it takes, no matter what program you use.

There is a log file written to `._sync_nextcloud/nextcloudcmd.txt`, or you can change its location with the `--logdir` option.
