### ISSUE TITLE
Skipping?

### ISSUE THREAD

**Issue by johncadengo** [qcif/nextcloud-sync-cron#8]
When I run the script, with the `--verbose` option, I get this output

```nextcloud-sync-cron.sh: skipping (can sync in 3868s)```

What does it mean and how can I fix it?

**Comment by johncadengo** [comment]
Ok, I was able to figure out why by looking at the files in the `._sync_nextcloud` folder in my nextcloud folder.

**Comment by hoylen** [comment]
Good.

It means _nextcloudcmd_ produced an error the previous time it ran, so it is not going to run it again at this time. It is going to wait for a delay period before running it again.

 Look inside the `._sync_nextcloud/failures.txt` (inside the `local` directory you have configured) for details about the error.

This delay gets longer and longer if _nextcloudcmd_ keeps producing errors.

For example, if you have set up your _cron_ job (or systemd timer) to run _nextcloud-sync-cron_ every minute and a network outage causes _nextcloudcmd_ to fail, you don't want it to still keep trying every minute and keep failing. Instead it will only try to run _nextcloudcmd_ in 2 minutes, 4 minutes, etc., but the maximum skipping delay is 24 hours. So if the problem persists, it will only run _nextcloudcmd_ once every day until the problem is fixed; skipping the rest.
