### ISSUE TITLE
Cronjob does not execute sync job

### ISSUE THREAD

**Issue by danielsteiner** [qcif/nextcloud-sync-cron#9]
Hi,

i am not entirely sure if this is a problem with this script or with my raspberry but I configured everything as described in the readme & it runs perfectly when executed manually but it seems as if the cronjob is not executed. Have you got any idea how to debug this?

**Comment by hoylen** [comment]
Look at the output in the log directory (which is specified with the `--logdir` option, or defaults to `._sync_nextcloud` inside the local source directory). See what it produces for a manually executed run, then compare it to what happens when it is run by a _cron_ job.

If you suspect the _cron_ job isn't running, replace the _nextcloud-sync-cron.sh_ with your own debug script, to check if _cron_ is running it when you expected it to run.

Make sure paths are all absolute paths and not relative paths.

Check directory and file permissions.

**Comment by danielsteiner** [comment]
Hi, I haven't had time to look further into this earlier but now I've installed NC & this script on another pi and it still does not work. Syncing works fine if I manually invoke the nextcloudcmd command but will not sync if run via cron. I know, that the script is executed since I am pinging my healthcheck.io service after the sync is done. 

Syncinc manually via nextcloudcmd works fine (both directions) but not via cron so I suspect, that this is not directly a problem with this script but rather with raspbian or something else.

**Comment by hoylen** [comment]
You'll need to find time to look in the log files, to find out why it failed. Without further information, there is nothing I can do to help.
